# CLEANING AND MERGING DATAFRAMES

--------

##### Imports

In [13]:

import pandas as pd

--------

##### Read in the files

In [14]:
# Directors

directors = pd.read_csv('DATA/Directors.csv', index_col=False)
directors.sample(n=10, random_state=1)

,Unnamed: 0,movie_id,person_id,primary_title,original_title,start_year,runtime_minutes,genres,averagerating,numvotes,primary_name,birth_year,death_year,primary_profession
47151,101614,tt1792806,nm2258329,Indemnity,Indemnity,2012,51.0,"Drama,Horror,Mystery",3.7,52,David Dietz,1970.0,NaN,"actor,cinematographer,producer"
20431,44752,tt2401213,nm0685526,Ivan the Powerful,Ivan Syla,2013,NaN,Adventure,7.4,261,Igor Pismennyy,1966.0,NaN,"actor,director,writer"
77835,165945,tt5108932,nm4437163,Five to Nine,Five to Nine,2015,90.0,Crime,5.8,15,Tay Bee Pin,NaN,NaN,"producer,director"
63157,134968,tt4984930,nm0753393,The Messenger,The Messenger,2015,89.0,"Documentary,Family",7.7,87,Su Rynard,NaN,NaN,"director,assistant_director,writer"
11641,26243,tt2094110,nm4741086,Sayonara Speed Tribes,Sayonara Speed Tribes,2012,45.0,"Action,Biography,Documentary",7.8,9,Jamie Morris,NaN,NaN,"cinematographer,producer,editor"
78932,168026,tt2507346,nm0330641,Blood and Circumstance,Blood and Circumstance,2014,97.0,"Crime,Drama,Mystery",6.7,18,Tim Gordon,NaN,NaN,"cinematographer,camera_department,director"
64659,137516,tt4121522,nm6276572,Shuruaat Ka Interval,Shuruaat Ka Interval,2014,99.0,Drama,7.5,59,Ankit Tripathi,NaN,NaN,"director,writer,cinematographer"
69135,146262,tt3397992,nm1891313,Prom Ride,Prom Ride,2015,86.0,"Horror,Thriller",3.4,274,Kazeem Molake,NaN,NaN,"producer,miscellaneous,production_manager"
10740,24091,tt3374816,nm4485521,Wild in Blue,Wild in Blue,2015,82.0,"Romance,Thriller",5.5,1248,Matthew Berkowitz,NaN,NaN,"producer,editor,director"
29541,66093,tt1976003,nm0614880,Things Never Said,Things Never Said,2013,112.0,Drama,6.6,347,Charles Murray,NaN,NaN,"producer,miscellaneous,writer"

In [15]:
# tmdb file

TMDB1 = pd.read_csv('DATA/tmdb_movies_1.csv')
TMDB1.sample(n=10, random_state=1)

,ID,Title,Release Date,Popularity,Vote Average,Vote Count,Budget,Revenue,Runtime,Genres,Original Language,Production Companies,Production Countries,Overview,Tagline,Status,Director
824,13394,Shrek the Halls,2007-11-28,19.818,6.361,837,60000000,0,28,"Adventure, Animation, Comedy, Fantasy, Family",en,"DreamWorks Animation, Pacific Data Images",United States of America,The Christmas tree isn't the only thing green ...,NaN,Released,Gary Trousdale
255,544757,The Garden,2002-08-20,0.588,0.000,0,0,0,0,"Fantasy, Drama",en,NaN,NaN,Ben misses his father who has locked himself a...,NaN,Released,Peter Bunzl
238,1116835,Toss of the Coin,2002-10-01,0.001,0.000,0,0,0,12,Fantasy,en,NaN,NaN,Emissaries of Heaven and Hell arrive upon the ...,NaN,Released,Patrick Steele
809,18547,The Ferryman,2007-01-01,3.805,4.500,34,0,0,100,"Horror, Thriller, Fantasy",en,"Lipsync Productions, General Film Corporation,...","New Zealand, United Kingdom","Out on a dead calm ocean, in a thick fog, a gr...",NaN,Released,Chris Graham
216,11852,The Hot Chick,2002-12-13,37.969,6.349,1975,0,54639553,104,"Comedy, Fantasy",en,"Touchstone Pictures, Happy Madison Productions",United States of America,Not only is Jessica Spencer the most popular g...,The hottest chick in town just switched bodies...,Released,Tom Brady
385,11451,Herbie Fully Loaded,2005-06-22,30.626,5.777,2244,50000000,144100000,100,"Comedy, Family, Adventure, Fantasy, Romance",en,"Walt Disney Pictures, Robert Simonds Productions",United States of America,"Maggie Peyton, the new owner of Number 53 - th...",Start your engines...,Released,Angela Robinson
452,577142,Goosebumps: Night of the Living Dummy III,2004-09-07,1.259,8.400,7,0,0,44,"Family, Fantasy, Horror",en,"Protocol Entertainment, Scholastic Productions...",Canada,Trina and her brother Dan think dad's dummies ...,Every dummy has his day.. or night,Released,Timothy Bond
453,572926,Alice's Misadventures in Wonderland,2004-09-24,0.883,10.000,1,0,0,0,Fantasy,en,NaN,NaN,A contemporary remake of Lewis Carroll's class...,We're All mad here.,Released,Robert Rugan
8,5994,The Family Man,2000-12-12,19.567,6.799,1919,60000000,124700000,125,"Comedy, Drama, Romance, Fantasy",en,"Beacon Pictures, Saturn Films, Universal Pictures",United States of America,"Jack's lavish, fast-paced lifestyle changes on...",What if you made different choices? What if yo...,Released,Brett Ratner
437,831226,El segundo,2004-04-25,0.827,0.000,0,0,0,87,"Fantasy, Western",en,Ramblin' Tank Productions,United States of America,A Tejano rancher hires an oil worker (Hank Jac...,A Metaphysical Western,Released,Hank Jacobs

In [16]:
TMDB2 = pd.read_csv('DATA/tmdb_movies_2.csv')
TMDB2.sample(n=10, random_state=1)

,ID,Title,Release Date,Popularity,Vote Average,Vote Count,Budget,Revenue,Runtime,Genres,Original Language,Production Companies,Production Countries,Overview,Tagline,Status,Director
608,75507,Dragon Crusaders,2011-09-27,3.923,2.500,32,0,0,90,"Fantasy, Action, Science Fiction",en,The Asylum,United States of America,"In this sword-and-sorcery extravaganza, a grou...",Holy Warriors Must Battle an Army of Demons,Released,Mark Atkins
1695,252360,In the Name of the King III,2014-02-05,8.026,3.563,71,3500000,0,85,"Action, Adventure, Drama, Fantasy",en,"Event Film Distribution, Bolu Filmproduktion u...","Germany, Canada","Hazen Kaine, an American contract killer livin...",NaN,Released,Uwe Boll
790,666782,Jabberwocky,2012-01-01,0.249,0.000,0,0,0,8,"Horror, Science Fiction, Fantasy",en,NaN,United States of America,"Imprisoned in a winter wonderland, Alice and t...",NaN,Released,Ted Eschweiler
650,47065,Tales of an Ancient Empire,2010-07-31,6.140,3.065,23,1000000,0,86,"Adventure, Fantasy, Horror, Action, Thriller, ...",en,NaN,"Argentina, United States of America",A princess is on a quest to unite the five gre...,NaN,Released,Albert Pyun
1634,298115,Dragons: Dawn of the Dragon Racers,2014-11-01,22.351,7.200,339,0,0,26,"Animation, Family, Adventure, Comedy, Fantasy",en,DreamWorks Animation,United States of America,A hunt for a lost sheep turns into a competiti...,NaN,Released,Elaine Bogan
625,61870,Billy Owens and the Secret of the Runes,2010-01-01,1.396,4.667,6,0,0,81,"Adventure, Family, Fantasy, Science Fiction",en,"Artist View Entertainment, Mystical Films, Sky...",United States of America,Three students have to find a way to free thei...,NaN,Released,Mark McNabb
763,852766,The Shadows,2013-05-30,0.008,0.000,0,0,0,60,"Fantasy, Horror",en,NaN,NaN,Boston fantasy,NaN,Released,Alexi Reibman/Jessie Alperin/Tayler Stander
447,453263,Write A Book About It,2010-04-13,0.368,9.000,1,0,0,114,"Comedy, Fantasy, Mystery, Science Fiction",en,NaN,United States of America,Tipsy Canoe (Actually Huizenga) was once an in...,Fame and Youth is an addiction,Released,Actually Huizenga
1499,361995,The Brink,2015-08-07,0.647,8.000,1,0,0,8,"Fantasy, Drama",en,JuVee Productions,United States of America,"Lost in an endless wasteland, two survivors cl...",NaN,Released,Ben Jendras
888,366297,Consumed,2013-11-05,0.329,0.000,0,3,0,5,Fantasy,en,Will Mayo Film,United States of America,"A parable of fire and grace, hand-scratched on...",Do you want to see an angel?,Released,Will Mayo

In [17]:
TMDB3 = pd.read_csv('DATA/tmdb_movies_3.csv')
TMDB3.sample(n=10, random_state=1)

,ID,Title,Release Date,Popularity,Vote Average,Vote Count,Budget,Revenue,Runtime,Genres,Original Language,Production Companies,Production Countries,Overview,Tagline,Status,Director
1688,956638,Fortuitous Beauty,2022-12-31,0.085,0.000,0,250,0,4,Fantasy,en,NaN,NaN,"A man visits a photo gallery, and reminisces a...",NaN,Released,Timothy McCourt
1392,1326677,The LEGO Movie 3: An Awesome Dimension Adventure,2022-06-03,1.180,0.000,0,0,0,67,"Adventure, Fantasy, Science Fiction, Comedy",en,LYCU Studios,NaN,2 years after the events of The LEGO Movie 2: ...,The Multiverse Opens,Released,The Lego Knight Studios
2463,1136726,Mermaids' Lament,2023-06-25,4.420,10.000,2,0,0,90,"Drama, Fantasy",en,NaN,United States of America,A woman drowning in trauma takes a therapist b...,"Moments away from drowning, she became the sea.",Released,G.B. Hajim
825,879645,Cosmic Connection,2020-05-26,0.266,7.000,1,0,0,2,Fantasy,en,NaN,NaN,Building worlds is easier when you're together.,NaN,Released,Xenia Leblanc
1333,425909,Ghostbusters: Afterlife,2021-11-18,37.316,7.386,4534,75000000,204334455,124,"Fantasy, Comedy, Adventure, Science Fiction",en,"Columbia Pictures, Bron Studios, The Montecito...","Canada, United States of America",When single mom Callie and her two kids Trevor...,Discover the past. Protect the future.,Released,Jason Reitman
1129,673546,Puppet Tears,2020-03-03,0.093,10.000,1,0,0,0,"Comedy, Fantasy, Drama",en,NaN,United Kingdom,A man wakes up one morning to discover he has ...,NaN,Released,Toby Gribben
703,1070492,Acid Rain,2020-06-20,0.188,0.000,0,500,500,13,"Drama, Fantasy, Action",en,NaN,NaN,Acid Rain is set in world where a mysterious i...,"One man's quest to save humanity in a dark, de...",Released,Oliver Finlinson
1765,903066,Lepidopterist,2021-03-27,0.505,0.000,0,0,0,0,"Science Fiction, Fantasy",en,"Toothpix, Triskelle Pictures",United Kingdom,A young scientist drives away from a lab with ...,NaN,Released,Sophie Black
2350,1193208,Marshall in Wonderland,2023-12-19,2.264,10.000,1,2000,0,64,"Comedy, Fantasy",en,NaN,NaN,"Marshall, a lazy couch dweller, gets thrown in...",How queer,Released,Brandon Rose
1290,550440,Timmy Failure: Mistakes Were Made,2020-01-25,10.408,6.230,174,45000000,0,99,"Family, Mystery, Comedy, Fantasy",en,"Walt Disney Pictures, Whitaker Entertainment, ...",United States of America,An 11-year old boy believes that he is the bes...,Small detective. Big imagination.,Released,Tom McCarthy

In [18]:
# concatinate the three TMDB files

TMDB_FULL = pd.concat([TMDB1, TMDB2, TMDB3], ignore_index=True)

In [19]:
TMDB_FULL.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5452 entries, 0 to 5451
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ID                    5452 non-null   int64
 1   Title                 5452 non-null   object
 2   Release Date          5452 non-null   object
 3   Popularity            5452 non-null   float64
 4   Vote Average          5452 non-null   float64
 5   Vote Count            5452 non-null   int64
 6   Budget                5452 non-null   int64
 7   Revenue               5452 non-null   int64
 8   Runtime               5452 non-null   int64
 9   Genres                5451 non-null   object
 10  Original Language     5452 non-null   object
 11  Production Companies  3337 non-null   object
 12  Production Countries  3875 non-null   object
 13  Overview              5410 non-null   object
 14  Tagline               2267 non-null   object
 15  Status                5452 non-null   object
 16  Director              5269 non-null   object
dtypes: float64(2), int64(5), object(10)
memory usage: 724.2+ KB

In [20]:
TMDB_FULL.to_csv('CLEANDATA/tmdb_full.csv', index=False)